In [17]:
import pandas as pd

In [18]:
dd_prediction = pd.read_csv('data.csv')

In [19]:
data = dd_prediction.copy()

In [20]:
target = 'Label'

In [21]:
encode = ['Jenis Kelamin', 'Ruam Kulit', 'Manifestasi perdarahan', 'Kegagalan Sirkulasi', 'Syok berat', 'Uji Tokniket', 'Kebocoran Plasma', 'Pendarahan spontan']

In [ ]:
data

In [23]:
for col in encode:
  dummy = pd.get_dummies(data[col], prefix=col)
  data = pd.concat([data, dummy], axis = 1)
  del data[col]

In [29]:
data

,Umur,Suhu,Ruam Kulit,Manifestasi perdarahan,Kegagalan Sirkulasi,Syok berat,Uji Tokniket,Kebocoran Plasma,Pendarahan spontan,Trombositopenia,Peningkatan Hematokrit,Label,Jenis Kelamin_L,Jenis Kelamin_P
0,25,40,0,0,0,0,0,0,0,150000,0,0,0,1
1,30,39,0,0,0,0,0,0,0,150000,0,0,1,0
2,40,41,0,0,0,0,0,0,0,140000,0,0,1,0
3,23,39,1,1,0,0,0,0,0,150000,0,0,0,1
4,20,39,0,0,0,0,0,0,0,150000,0,0,1,0
5,32,40,0,0,0,0,0,0,0,145000,0,0,0,1
6,22,40,0,0,0,0,0,0,0,145000,5,0,1,0
7,45,39,0,0,0,0,0,0,0,150000,5,0,1,0
8,21,39,1,0,0,0,0,0,0,140000,10,0,0,1
9,28,40,0,0,0,0,0,0,0,155000,0,0,1,0
10,44,40,0,0,0,0,0,0,0,120000,15,0,1,0
11,51,40,1,0,0,0,0,0,0,134000,14,0,1,0
12,41,39,1,0,0,0,0,0,0,120000,5,0,1,0
13,45,39,1,0,0,0,0,0,0,145000,3,0,0,1
14,29,39,1,1,0,0,0,0,0,143500,3,0,1,0
15,20,39,1,1,0,0,0,0,0,98000,10,0,1,0
16,42,40,1,0,0,0,0,0,0,142500,3,0,1,0
17,20,40,1,0,0,0,0,0,0,135000,17,0,0,1
18,36,39,0,0,0,0,0,0,0,140000,13,0,0,1
19,38,40,1,1,1,1,1,1,1,98000,28,1,1,0
20,23,39,1,1,0,0,1,1,0,95000,20,1,0,1
21,33,39,1,1,0,0,1,1,0,82000,20,1,0,1
22,35,40,1,1,0,0,1,1,0,100000,21,1,1,0
23,43,40,1,1,0,0,1,1,0,93000,21,1,0,1
24,47,40,1,1,0,0,1,1,0,67000,27,1,1,0
25,39,40,1,1,0,0,1,1,0,96000,25,1,0,1
26,30,39,1,1,0,0,1,1,0,90000,21,1,0,1
27,46,39,1,1,0,0,1,1,0,90000,22,1,1,0
28,23,40,1,1,0,0,1,1,0,99000,21,1,0,1
29,49,41,1,1,0,0,1,1,0,97000,24,1,0,1
30,38,39,1,1,0,0,1,1,0,76000,26,1,0,1

In [25]:
X = data.drop('Label', axis = 1)
Y = data['Label']

In [ ]:
Y

In [26]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, Y)

GaussianNB()

In [28]:
import pickle
pickle.dump(model, open('model_dd.pkl', 'wb'))